# fly.toml file generated for lsm-discord-bot on 2022-09-30T17:32:56-07:00

app = "lsm-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

